### ISSUE TITLE
Pressure closure constants need to be made consistent with documentation

### ISSUE THREAD

**Issue by BrodiePearson** [vanroekel/MPAS-Model#15]
The current model uses a mix of conventions for naming the closure constants that arise from the pressure terms in second- and third-moment budgets. ***We need to make these constants consistent with our documentation on Overleaf.*** 

The choice of constants in the documentation are designed to be clearer, more consistent across different physical pressure terms, and trivial to expand for the effects due to surface waves. The table below summarizes the constants in our model vs. existing closure schemes (note that Stokes drift terms are not presently in the closure scheme, but will be added in future PRs). In the Fortran script, greek symbols will be written by their full name, superscripts, and the naming convention will be `{variable name}_{superscripts}_{subscripts}` (if there are no sub- or super-scripts they will be neglected in this naming). For the tracer constants, the symbols containing $\phi$ will have $\phi$ replaced by $tracer$. (i.e. $C^{slow}$ will be `C_slow`, $\alpha_2$ will be `alpha_2`, and $\alpha^{st}_{\phi 2}$ will be `alpha_st_tracer2`

<img src="https://user-images.githubusercontent.com/43418592/120393827-70c31880-c2e7-11eb-9ef8-3b95c766d788.png" alt="drawing" width="600"/>

**Comment by BrodiePearson** [comment]
For my future reference the process for adding/modifying the parameters of the scheme is (example uses existing parameter `c_2`):

1. Add the new parameter to `mpas_ocn_turbulence.F` (in this case `c_2`), and connect it to the chosen namelist variable (`config_adc_c2 `) https://github.com/vanroekel/MPAS-Model/blob/5dc8d6e40e31fb03492426e324d435637f6edf05/src/core_ocean/shared/mpas_ocn_turbulence.F#L167
2. Also in `mpas_ocn_turbulence.F`, define the type of the variable and give it an initial zero value https://github.com/vanroekel/MPAS-Model/blob/5dc8d6e40e31fb03492426e324d435637f6edf05/src/core_ocean/shared/mpas_ocn_turbulence.F#L46-L48 https://github.com/vanroekel/MPAS-Model/blob/5dc8d6e40e31fb03492426e324d435637f6edf05/src/core_ocean/shared/mpas_ocn_turbulence.F#L1195
3. Add namelist variable to registry, with short description and default value https://github.com/vanroekel/MPAS-Model/blob/5dc8d6e40e31fb03492426e324d435637f6edf05/src/core_ocean/adc_mixing/Registry_adc_mixing_fields_opts.xml#L50-L52
4. Add the new parameter into the ADC scheme (Fortran is not case sensitive) https://github.com/vanroekel/MPAS-Model/blob/5dc8d6e40e31fb03492426e324d435637f6edf05/src/core_ocean/shared/mpas_ocn_adcReconstruct.F#L571

This should allow the MPAS-Model to compile and create the `ocean_model` executable. **NOTE: if you have already compiled MPAS-Model, you will have to run `make clean` before running `make gfortran CORE=ocean`, or the namelist changes will produce an error**. 

Then in your forward run directory, update the `namelist.ocean` file to include the new namelist variable (in this case `config_adc_c2 `)

**Comment by BrodiePearson** [comment]
Constants that are to be added to scheme and the ones they replace `ADC code parameter (namelist parameter)`:
- [ ] `C_2 (config_adc_c2)` and `[1-beta5] (config_adc_beta5)` $\rightarrow$ `C_b (config_adc_c_b)`
- [ ] `alpha1 & alpha2` (no namelist parameters) $\rightarrow$ `alpha_1 & alpha_2 (config_adc_alpha_1, config_adc_alpha_2)` (**Why are w't' production terms zeroed?**)
- [ ] `gamma1 (config_adc_gamma1)` $\rightarrow$ `C_b_tracer (config_adc_c_b_tracer)`
- [ ] `0.8 constant (no namelist parameter)` $\rightarrow$ `alpha_0 (config_adc_alpha_0)` **This is first rapid pressure coefficient**
- [ ] `alpha3 (config_adc_alpha3)` $\rightarrow$ `alpha_tracer1 & alpha_tracer2 (config_adc_alpha_tracer1 & config_adc_alpha_tracer2)` **Note the previous version uses the single-parameter closure of [Canuto 2001](https://journals.ametsoc.org/view/journals/phoc/31/6/1520-0485_2001_031_1413_otpiop_2.0.co_2.xml), now generalized to a two-parameter closure [following Mironov 2001](https://rmets.onlinelibrary.wiley.com/doi/pdf/10.1002/qj.49712757106?casa_token=tYy156dAEgsAAAAA:jH6160d1kpnVHBKxDlBPzuyyvAn8m-UVZ6oQP2sj1o4OEp6TsJ1kIOTZZ_SHX6FzoMdUiD-BlIJKkyU). The default values are the Canuto 2001 closure equivalent to `alpha3 = 0.8`**
- [ ] `cVel [config_adc_cVel]` $\rightarrow$ `C_slow [config_adc_c_slow]`
- [ ] `cvVel [config_adc_cwVel]` $\rightarrow$ a new coefficient `slow_w_factor [config_adc_slow_w_factor]` **This multiplies `C_slow` to adjust vertical velocity decay rate, default is 0.875, equivelent to previous parameters**
- [ ] `cSalt & cTemp [config_adc_cTemp & config_adc_cSalt]` $\rightarrow$ a single term `C_slow_tracer [config_adc_c_slow_tracer ]` **These coefficients were identical by default previously**
- [ ] Also removed several parameters that are never used by ADC scheme: `c_1 [config_adc_c1], c1, c2, c8, c10`, as it is never used

**Comment by vanroekel** [comment]
addressed by #17
