### ISSUE TITLE
Issues with transport terms in $\overline{w'w'w'}$ budget

### ISSUE THREAD

**Issue by BrodiePearson** [vanroekel/MPAS-Model#7]
@vanroekel After talking Amrapalli today (I don't seem to be able to tag her; I'll email this as well) and reflecting/reading a bit, I have a potential suggestion for the transport term in the $\overline{w'w'w'}$ budget (apologies if you have already thought of this). 

It seemed that the current issue is with the transport term in the $\overline{w'w'w'}$ budget:

$\frac{\partial \overline{w'w'w'}}{\partial t} \sim -\frac{\partial \overline{w'w'w'w'}}{\partial z} + \frac{3}{2}\frac{\partial (\overline{w'w'})^2}{\partial z}$

This can be re-arranged in several ways, but perhaps the easiest is to combine these two transport terms by noting that under the mass-flux assumption; $\overline{w'w'w'w'}=(1+S_w^2)(\overline{w'w'})^2$ (Eq. 13 of [Gryanik & Hartmann 2001](https://journals.ametsoc.org/view/journals/atsc/59/18/1520-0469_2002_059_2729_atcftc_2.0.co_2.xml)). Then,

$\frac{\partial \overline{w'w'w'}}{\partial t} \sim -\frac{\partial \left[(-\frac{1}{2}+S_w^2)(\overline{w'w'})^2\right]}{\partial z}$.

However, you are finding that the mass-flux approximation for $\overline{w'w'w'w'}$ is much smaller than the LES profile of $\overline{w'w'w'w'}$, and a better approximation for this profile is the quasi-normal approximation $\overline{w'w'w'w'}=3(\overline{w'w'})^2$, which yields,

$\frac{\partial \overline{w'w'w'}}{\partial t} \sim -\frac{\partial \left[\frac{3}{2}(\overline{w'w'})^2\right]}{\partial z}$.

Contrasting the mass flux and quasi-normal forms of this transport term, they are only identical for $S_w=\sqrt{2}$. **For example, for equal-sized plumes $\sigma=0.5$, the mass flux estimate of $\overline{w'w'w'w'}$ is three times smaller than the quasi-normal estimate - perhaps explaining your LES results.**

Perhaps we should be using something like the [Gryanik & Hartmann 2001](https://journals.ametsoc.org/view/journals/atsc/59/18/1520-0469_2002_059_2729_atcftc_2.0.co_2.xml) closure for this term (their Eq. 27);

$\overline{w'w'w'w'}=3(1+\frac{1}{3}S_w^2)(\overline{w'w'})^2$

which 

1. Tends towards the quasi-normal approximation when $S_w^2\rightarrow 0$ and $\sigma\rightarrow 0.5$ (when mass-flux closure becomes less appropriate)
2. Tends towards the mass-flux approximation $\overline{w'w'w'w'}\approx S_w^2 (\overline{w'w'})^2$ when $S_w^2$ is large and $\sigma$ is small (when the quasi-normal approximation becomes inappropriate)
3. Satisfies realizability constraints that the quasi-normal approximation does not guarantee (I think...see Section 5 of [Gryanik et al, 2005](https://journals.ametsoc.org/view/journals/atsc/62/7/jas3457.1.xml))
4. Unfortunately this isn't as natural as the transition between non-local to down-gradient fluxes as $\sigma\rightarrow 0.5$, but I'm not sure I have a better suggestion

**Comment by katsmith133** [comment]
I believe this issue was addressed in full by PR #11, but correct me if I am wrong. Shall we close it?

**Comment by BrodiePearson** [comment]
I agree this is closed now!
